MATCH_MODE_MATCH_FIELDS = "Match Fields"
MATCH_MODE_IDENTITY_FIELDS = "Identity Fields"
MATCH_MODES = (MATCH_MODE_MATCH_FIELDS, MATCH_MODE_IDENTITY_FIELDS)

SYNC_DEFINITION = "Sync Definition"
SYNC_PARTNER = "Sync Partner"
SYNC_PARTNER_TYPE = "Sync Partner Type"
SYNC_RUN = "Sync Run"
SYNC_RUN_ITEM = "Sync Run Item"
SYNC_SETTINGS = "Sync Settings"

MAPPING_DIRECTION_BOTH = "Frappe <-> Partner"
MAPPING_DIRECTION_FRAPPE_TO_PARTNER = "Frappe -> Partner"
MAPPING_DIRECTION_PARTNER_TO_FRAPPE = "Frappe <- Partner"
MAPPING_DIRECTIONS = (
	MAPPING_DIRECTION_BOTH,
	MAPPING_DIRECTION_FRAPPE_TO_PARTNER,
	MAPPING_DIRECTION_PARTNER_TO_FRAPPE,
)

TRIGGER_MANUAL = "manual"
TRIGGER_SCHEDULER = "scheduler"
TRIGGER_API = "api"
VALID_TRIGGER_TYPES = (TRIGGER_API, TRIGGER_MANUAL, TRIGGER_SCHEDULER)

RUN_STATUS_QUEUED = "Queued"
RUN_STATUS_RUNNING = "Running"
RUN_STATUS_SUCCESS = "Success"
RUN_STATUS_PARTIAL_ERROR = "Partial Error"
RUN_STATUS_NEEDS_REVIEW = "Needs Review"
RUN_STATUS_ERROR = "Error"
RUN_STATUS_SKIPPED = "Skipped"
RUN_STATUS_PREVIEW = "Preview"
ACTIVE_RUN_STATUSES = (RUN_STATUS_QUEUED, RUN_STATUS_RUNNING)
DONE_RUN_STATUSES = (
	RUN_STATUS_ERROR,
	RUN_STATUS_NEEDS_REVIEW,
	RUN_STATUS_PARTIAL_ERROR,
	RUN_STATUS_SKIPPED,
	RUN_STATUS_SUCCESS,
)

TIMESTAMP_TIE_MANUAL = "Manual"
TIMESTAMP_TIE_FRAPPE_WINS = "Frappe Wins"
TIMESTAMP_TIE_PARTNER_WINS = "Partner Wins"
TIMESTAMP_TIE_BREAKERS = (
	TIMESTAMP_TIE_FRAPPE_WINS,
	TIMESTAMP_TIE_MANUAL,
	TIMESTAMP_TIE_PARTNER_WINS,
)

ONE_WAY_MATCH_FIRST = "first_match"
ONE_WAY_MATCH_ALL = "all_matches"
ONE_WAY_MATCH_MODES = (ONE_WAY_MATCH_ALL, ONE_WAY_MATCH_FIRST)

FRAPPE_WRITE_ACTION_NONE = "None"
FRAPPE_WRITE_ACTION_SUBMIT = "Submit"
FRAPPE_WRITE_ACTIONS = (
	FRAPPE_WRITE_ACTION_NONE,
	FRAPPE_WRITE_ACTION_SUBMIT,
)

CONFLICT_POLICY_NEWEST_WINS = "newest_wins"
CONFLICT_POLICIES = (CONFLICT_POLICY_NEWEST_WINS,)

VALUE_MAPPING_FALLBACK_KEEP_ORIGINAL = "keep_original"
VALUE_MAPPING_FALLBACK_USE_FALLBACK = "fallback"
VALUE_MAPPING_FALLBACK_USE_NULL = "null"
VALUE_MAPPING_FALLBACK_ACTIONS = (
	VALUE_MAPPING_FALLBACK_KEEP_ORIGINAL,
	VALUE_MAPPING_FALLBACK_USE_FALLBACK,
	VALUE_MAPPING_FALLBACK_USE_NULL,
)
UNMAPPED_ACTION_KEEP_ORIGINAL = "Keep Original"
UNMAPPED_ACTION_USE_FALLBACK = "Use Fallback Value"
UNMAPPED_ACTION_USE_NULL = "Use NULL"
UNMAPPED_ACTIONS = (
	UNMAPPED_ACTION_KEEP_ORIGINAL,
	UNMAPPED_ACTION_USE_FALLBACK,
	UNMAPPED_ACTION_USE_NULL,
)
UNMAPPED_ACTION_KEYS = {
	UNMAPPED_ACTION_KEEP_ORIGINAL: VALUE_MAPPING_FALLBACK_KEEP_ORIGINAL,
	UNMAPPED_ACTION_USE_FALLBACK: VALUE_MAPPING_FALLBACK_USE_FALLBACK,
	UNMAPPED_ACTION_USE_NULL: VALUE_MAPPING_FALLBACK_USE_NULL,
}
